from backend_api.user import User as User

class Workspace:
    id: str
    owner: str
    instances: list[str]
    def __init__(
        self, *, id: str = ..., owner: str = ..., instances: list[str] = ...
    ) -> None: ...
    def toJson(self) -> dict: ...
    @staticmethod
    async def new(user: User) -> Workspace: ...
    @staticmethod
    async def get(id: str) -> Workspace: ...
    @staticmethod
    async def delete(id: str) -> None: ...
